### ISSUE TITLE
cb() never called

### ISSUE THREAD

**Issue by thfrlw** [rezzza/gulp-uglifycss#15] opened 2017-03-28 10:40 UTC
as of today couple hours ago I receive cb() never called from npm install

**Comment by jonicious** [comment] 2017-03-28 11:30
I am experiencing the same issue. v1.0.7 seems to break things. FYI: Running npm version `3.10.10` and Node version `v6.10.1`. Downgrading to v1.0.6 works as a workaround.

**Comment by ccapndave** [comment] 2017-03-28 12:03
I'm also experiencing this.  If you install via `yarn` instead of `npm` it gives the following error, if its relevant:

`error An unexpected error occurred: "https://registry.yarnpkg.com/gulp-uglifycss/-/gulp-uglifycss-1.0.7.tgz: invalid tar file".`

**Comment by cbxp** [comment] 2017-03-28 13:21
I am also experiencing this. We have 1.0.6 in package.json and this has worked for a long time. Neither this nor 1.0.7 work now.

**Comment by gdvsbp** [comment] 2017-03-28 20:46
Encountered issue here as well w/ npm 4.1.1 and node 4.6.2, and elsewhere with npm 2.13.2 and node 6.6.0

**Comment by Jiish** [comment] 2017-03-29 03:25
Same issue here with 1.0.6. "npm install" brings "cb() never called". It seems this started to occur on our build machines right after this 1.0.7 package update to npm

**Comment by Spy-Seth** [comment] 2017-03-29 07:25
I've publish a maintenance version yesterday (v1.0.7). I've used `yarn publish` to publish it. I think this could be an explanation of this. 

I just publish a new version (v1.0.8) of the package using `npm publish` as before. Please tell me if this solve the issue.

**Comment by jonicious** [comment] 2017-03-29 07:30
@Spy-Seth Yes, using v1.0.8 fixes the issue for me. Thanks!

**Comment by Spy-Seth** [comment] 2017-03-29 07:41
The problem of corrupted package seems to already be reported on yarn site: https://github.com/yarnpkg/yarn/issues/2764#issuecomment-290008862 

Wait and see!

**Comment by Spy-Seth** [comment] 2017-03-29 07:43
Duplicate of https://github.com/rezzza/gulp-uglifycss/issues/14. Please report on the other thread if you keep having trouble.

**Closed by Spy-Seth** 2017-03-29 07:43 UTC
Labels: duplicate
